### ISSUE TITLE
Deployment/update error map: map[] does not contain declared merge key: name

### ISSUE THREAD

**Issue by niekappartmedia** [Azure/k8s-deploy#10] opened 2019-11-27 15:05 UTC
When i deploy the first time with k8s deploy everything works fine.
But when i deploy the second time i get the following error:

error calculating patch from openapi spec: map: map[] does not contain declared merge key: name

Strange though that when i deploy localy the firsttime with kubectl and update everything works fine.
But when k8s has deployed i even can not update with local kubectl i get the same error.

Any ideas what this could be?

This is the deployment yaml:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: test
      labels:
        app: test
    spec:
      securityContext:
        runAsGroup: 33
        fsGroup: 33
      volumes:
        - name: nfs-bucket
          persistentVolumeClaim:
            claimName: nfs-bucket
      containers:
        - name: test
          image: niek/test:develop
          imagePullPolicy: Always
          volumeMounts:
            - name: nfs-bucket
              mountPath: "/var/www/bucket"
          envFrom:
            - secretRef:
                name: test-secret
          ports:
            - name: 80tcp01
              containerPort: 80
              protocol: TCP
          stdin: true
          tty: true
      imagePullSecrets:
        - name: dockerhub
```

**Comment by niekappartmedia** [comment] 2019-11-29 09:43
So i am a bit further with this issue.

After testing and investigating.
When i update via kubectl -f it works when i comment the imagePullSecret.
After this step when i update again with imagePullSecret uncommented it works also also for azure/k8s-deploy. But after that when i again want to redeploy via azure/k8s-deploy i get the same error. So it looks like the imagePullSecrets are causing all te trouble. Not yet found the fix for this.

**Comment by lennartschoch** [comment] 2019-11-29 11:04
I am also experiencing this, but in a slightly different scenario:
I do not specify any imagePullSecrets, yet I get the same error.

What I thought is that kubectl was doing some weird transformation of the YAML file, causing it to map `"imagePullSecrets":[ "name":""]` (which seems to be the value that azure/k8s-deploy passes to kubectl) to `"imagePullSecrets":[map[]]` which is invalid because of the missing "name" key.

I am not sure why this is coming up right now, as azure/k8s-deploy did not change. Maybe it has to do something with the kubectl version. I will continue to look into this

**Comment by niekappartmedia** [comment] 2019-11-29 11:11
@lennartschoch 
I currently fixed it by removing the azure/k8s-deployment step en creating my own simple deployment step running the kubectl apply commands myself.

  # Deploy everything to the k8s cluster
      - name: Deploy to namespace on kubernetes cluster
        run: |
          kubectl apply -f k8s/redis.yaml -n ${{ env.NAMESPACE }}

But it seems like you already noticed it is some kind of strange format error.

**Comment by lennartschoch** [comment] 2019-11-29 14:13
I was digging into this a little deeper and found out the following:

Apparently, something changed regarding how GitHub actions handle non-defined input parameters (at least, this is the only plausible reason I can think of right now). This caused the pullImageSecrets parameters on the pipeline, if not defined, to be interpreted as an array with one empty string. Kubectl "optimizes" this to an empty map, which causes the validation error.

I created a PR which fixed this issue by filtering all pullImageSecrets which are empty or contain only whitespace.

@niekappartmedia My fork also has a release (v1-hotfix) which fixes this issue until the PR is merged. If you like to, you can try using `lennartschoch/k8s-deploy@v1-hotfix` in your pipeline temporarily and check whether that also solves the issue for you :)

**Comment by niekappartmedia** [comment] 2019-12-02 08:04
@lennartschoch I will check your merge commit.

**Comment by ds-ms** [comment] 2019-12-04 08:59
Shouldn't the section in your manifest look like this
`      containers: `
instead of
`      containerst`

**Comment by niekappartmedia** [comment] 2019-12-04 09:07
@ds-ms I see now what your meaning think i hit a wrong button while copying else the first deployment would have never worked. Because the yaml validator should have failed than.

**Comment by ds-ms** [comment] 2019-12-04 09:28
What is the error you're seeing in your logs? Could you enable debug and give me some verbose logs to look at?

**Comment by ds-ms** [comment] 2019-12-10 08:00
I suppose the issue is because of the imagepullrequests section in your deployment.yaml

If you're adding extra image pull secrets in the workflow; it ends up converting the single image pull secret which is like this `"imagePullSecrets":{"name":"n1"}` to `"imagePullSecrets":[{"name":"n1"},{"name":"n2"}]` the edit fails because of the conversion of object to object[]

**Closed** 2020-01-07 07:13 UTC
